# Generated by Django 2.2.3 on 2019-07-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('group', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
            ],
        ),
    ]
