# Generated by Django 2.2.3 on 2019-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
