# Generated by Django 2.2.3 on 2019-08-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_manager', '0002_auto_20190731_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_manager.Group'),
        ),
    ]
